import { useState } from "react";
import activePlan from "../data/activePlan.ts";
import { completedMileage, entriesForWeek, recommendWeek } from "../domain/progression.ts";
import type { RecommendationDecision, TrainingStore, WeeklyCheckIn } from "../domain/training.ts";
import { displayTrainingDate, trainingDateIso } from "../utils/trainingDate.ts";
import { resolveWorkoutStatus, strengthSessionIdForWorkout } from "../domain/workoutStatus.ts";

interface Props { store: TrainingStore; onSaveCheckIn: (checkIn: WeeklyCheckIn) => void; onSaveDecision: (decision: RecommendationDecision) => void; onOpenWorkout: (target: "today" | "strength", sessionId?: string) => void; }
const runCount = (week: typeof activePlan[number]) => week.workouts.filter((item) => item.kind === "run" || item.kind === "benchmark").length;

export default function CurrentPlanPage({ store, onSaveCheckIn, onSaveDecision, onOpenWorkout }: Props) {
  const today = trainingDateIso();
  const currentIndex = Math.max(0, activePlan.findIndex((week) => week.workouts.some((workout) => workout.date >= today)));
  const [openWeekId, setOpenWeekId] = useState(activePlan[currentIndex].id);
  const selectedWeek = activePlan.find((week) => week.id === openWeekId)!;
  const entries = entriesForWeek(selectedWeek, store.entries);
  const savedCheckIn = store.checkIns.find((item) => item.weekId === selectedWeek.id);
  const [checkIn, setCheckIn] = useState<WeeklyCheckIn>(savedCheckIn ?? { weekId: selectedWeek.id, sleepRecovery: "good", painAffectsMovement: false, confidence: "unchanged", longRunRecovery: "not-applicable" });
  const selectedIndex = activePlan.indexOf(selectedWeek);
  const weekEnd = selectedWeek.workouts.map((item) => item.date).sort().at(-1)!;
  const canCheckIn = weekEnd <= today && selectedIndex < activePlan.length - 1 && selectedWeek.plannedMiles > 0;
  const recommendation = recommendWeek(selectedWeek, entries, savedCheckIn, today);
  const selectWeek = (id: string) => { setOpenWeekId(id); setCheckIn(store.checkIns.find((item) => item.weekId === id) ?? { weekId: id, sleepRecovery: "good", painAffectsMovement: false, confidence: "unchanged", longRunRecovery: "not-applicable" }); };
  const status = (week: typeof activePlan[number]) => { const logged = entriesForWeek(week, store.entries); const runs = runCount(week); const resolved = logged.filter((item) => item.status === "completed" || item.status === "partial" || item.status === "skipped" || item.status === "substituted").length; const miles = completedMileage(logged); return resolved === 0 ? "Not started" : resolved >= runs ? "Completed" : `${resolved} of ${runs} runs · ${miles.toFixed(1)} of ${week.plannedMiles} miles`; };
  const selector = (week: typeof activePlan[number]) => <button className={week.id === openWeekId ? "week-selector is-active" : "week-selector"} type="button" key={week.id} onClick={() => selectWeek(week.id)}><span>Week {activePlan.indexOf(week) + 1}</span><strong>{week.plannedMiles} mi</strong><small>{status(week)}</small></button>;

  return <main className="current-plan-page"><header className="section-hero"><p className="goal-page__eyebrow">Specific prescription</p><h1>Current 8-Week Plan</h1><p>The rolling plan is adjusted from completed training and recovery—not automatically by the calendar.</p></header>
    {currentIndex > 0 && <details className="past-weeks"><summary>Past weeks ({currentIndex})</summary><div className="eight-week-strip">{activePlan.slice(0, currentIndex).map(selector)}</div></details>}
    <div className="eight-week-strip" aria-label="Current and upcoming weeks">{activePlan.slice(currentIndex).map(selector)}</div>
    <section className="active-week-card"><header><div><p className="goal-page__eyebrow">{selectedWeek.status}</p><h2>{selectedWeek.label}</h2><p>{selectedWeek.objective}</p></div><strong>{selectedWeek.plannedMiles} miles</strong></header><div className="active-workout-list">{selectedWeek.workouts.map((workout) => { const resolved = resolveWorkoutStatus(workout, selectedWeek, store); const pastLabel = resolved.state === "completed" ? "Completed" : resolved.state === "skipped" ? "Skipped" : workout.date < today ? "Not logged" : resolved.state === "shortened" ? "Shortened" : resolved.state === "suppressed" ? "Suppressed" : workout.date === today ? "Open today" : "Not due"; const strengthId = strengthSessionIdForWorkout(workout); return <article key={workout.id}><time dateTime={workout.date}>{displayTrainingDate(workout.date)}</time><div><strong>{workout.title}</strong><span>{resolved.availabilityReason}</span></div><div><strong>{resolved.duration}</strong><span>{pastLabel}</span>{resolved.canPreview && <button type="button" className="plan-workout-action" onClick={() => onOpenWorkout(resolved.sessionType === "strength" ? "strength" : "today", strengthId)}>{resolved.recommendedAction}</button>}</div></article>; })}</div></section>
    {canCheckIn && <section className="check-in-card"><div><p className="goal-page__eyebrow">End-of-week check-in</p><h2>How did the week land?</h2></div><form onSubmit={(event) => { event.preventDefault(); onSaveCheckIn(checkIn); }}><label>Sleep and recovery<select value={checkIn.sleepRecovery} onChange={(event) => setCheckIn({ ...checkIn, sleepRecovery: event.target.value as WeeklyCheckIn["sleepRecovery"] })}><option value="good">Good</option><option value="mixed">Mixed</option><option value="poor">Poor</option></select></label><label>Confidence<select value={checkIn.confidence} onChange={(event) => setCheckIn({ ...checkIn, confidence: event.target.value as WeeklyCheckIn["confidence"] })}><option value="improving">Improving</option><option value="unchanged">Unchanged</option><option value="declining">Declining</option></select></label><label>Long-run recovery<select value={checkIn.longRunRecovery} onChange={(event) => setCheckIn({ ...checkIn, longRunRecovery: event.target.value as WeeklyCheckIn["longRunRecovery"] })}><option value="within-48h">Within 24–48 hours</option><option value="slower">Longer than 48 hours</option><option value="not-applicable">Not applicable</option></select></label><label className="check-in-card__checkbox"><input type="checkbox" checked={checkIn.painAffectsMovement} onChange={(event) => setCheckIn({ ...checkIn, painAffectsMovement: event.target.checked })} /> Pain affected normal movement or running form</label><button className="run-log-form__save" type="submit">Save check-in</button></form>{savedCheckIn && <div className="recommendation-card recommendation-card--nested"><span className={`recommendation-badge recommendation-badge--${recommendation.state.toLowerCase()}`}>{recommendation.state}</span><div><h3>{recommendation.summary}</h3><ul>{recommendation.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div><div className="decision-actions"><button type="button" onClick={() => onSaveDecision({ weekId: selectedWeek.id, state: recommendation.state, accepted: true, decidedAt: new Date().toISOString() })}>Accept</button><button type="button" onClick={() => onSaveDecision({ weekId: selectedWeek.id, state: recommendation.state, accepted: false, decidedAt: new Date().toISOString() })}>Decline</button></div></div>}</section>}
  </main>;
}
