import { BODY_RECOMPOSITION_GOAL } from "../domain/strength.ts";

export default function GoalPage() {
  const goals = [
    { number: "01", title: "First 2027 benchmark half marathon", text: "Napa Spring Half Marathon — April 25, 2027, 7:00 a.m. Run healthy and controlled, then use the result to review future pace guidance.", metric: "Goal: measure progress without forcing pace", link: "https://napaspringhalf.com/" },
    { number: "02", title: "Monterey Bay Half Marathon", text: "Provisional November 2027 target. Confirm when officially announced.", metric: "Consider 10:00/mile only if comparable benchmarks support it", link: "https://www.montereybayhalfmarathon.org/" },
    { number: "03", title: "Optional spring 2028 endurance event", text: "Use an optional half marathon or supported long run to reinforce endurance and fueling without requiring an all-out performance.", metric: "Goal: prepare for marathon training" },
    { number: "04", title: "First full marathon", text: "Provisional fall 2028 target. Long Beach is the primary option and Santa Cruz is an alternative; confirm when official dates are announced.", metric: "Primary goal: finish strong", links: [["Long Beach", "https://runlongbeach.com/"], ["Santa Cruz", "https://www.runsantacruz.com/"]] },
  ];
  return <main className="goal-page"><header className="goal-page__hero"><p className="goal-page__eyebrow">2027–2028 Race Roadmap</p><h1>Go farther. Finish stronger.</h1><p className="goal-page__intro">Build sustainable speed and endurance through two half marathons before the first full marathon.</p></header><div className="goal-grid">{goals.map((goal) => <section className="goal-card" key={goal.number}><span className="goal-card__number">{goal.number}</span><h2>{goal.title}</h2><p>{goal.text}</p><p className="goal-card__metric">{goal.metric}</p>{goal.link && <a className="goal-card__link" href={goal.link} target="_blank" rel="noreferrer">Official race site <span aria-hidden="true">↗</span></a>}{goal.links && <div className="goal-card__options">{goal.links.map(([label, href]) => <a className="goal-card__link" href={href} target="_blank" rel="noreferrer" key={label}>{label} official site <span aria-hidden="true">↗</span></a>)}</div>}</section>)}</div><section className="goal-card goal-card--strength"><p className="goal-page__eyebrow">Strength + body composition</p><h2>A supportive secondary goal</h2><p>{BODY_RECOMPOSITION_GOAL}</p><p className="goal-card__metric">The plan prioritizes performance and body recomposition, not aggressive weight loss. See Strength → Guides for context.</p></section><aside className="knowledge-section__note"><strong>Need workout help?</strong> Open Strength → Guides for strength guidance. Running effort remains RPE-first; workout-specific steps are linked from the active plan.</aside></main>;
}
