import { useMemo, useState } from "react";
import activePlan from "../data/activePlan.ts";
import { aggregateWeeklyGraph, benchmarkPace, filterBenchmarks, filterByRange, GRAPH_THRESHOLDS, interpretBenchmarks, interpretConsistency, interpretEasyRuns, interpretLoad, interpretLongRuns, rangeStart, selectComparableEasyRuns, selectLongRuns } from "../domain/progressGraphs.ts";
import type { ProgressRange } from "../domain/progressGraphs.ts";
import { parseDurationMinutes } from "../domain/progression.ts";
import type { BenchmarkEntry, TrainingStore } from "../domain/training.ts";
import { trainingDateIso } from "../utils/trainingDate.ts";

const rangeLabels: Record<ProgressRange, string> = { "8w": "Last 8 weeks", "12w": "Last 12 weeks", "6m": "Last 6 months", all: "All data" };
const formatMinutes = (minutes: number | null) => minutes === null ? "Not prescribed" : `${Math.round(minutes)} min`;
const pointPosition = (value: number, min: number, max: number) => 88 - ((value - min) / Math.max(1, max - min)) * 76;

interface PlotPoint { id: string; date: string; value: number; label: string; tone?: string; marker?: string; }
function PointPlot({ title, description, points, lineValues, connect = true }: { title: string; description: string; points: PlotPoint[]; lineValues?: Array<number | null>; connect?: boolean }) {
  const minimum = title === "Easy-run pace" ? 3 : title === "Long-run durability" || title === "Benchmark history" ? 2 : 1;
  if (points.length < minimum) return <div className="chart-empty">Not enough comparable observations in this range.</div>;
  const values = [...points.map((point) => point.value), ...(lineValues ?? []).filter((value): value is number => value !== null)]; const min = Math.min(...values); const max = Math.max(...values);
  const coords = points.map((point, index) => ({ x: points.length === 1 ? 50 : 5 + index / (points.length - 1) * 90, y: pointPosition(point.value, min, max) }));
  connect = connect && title !== "Easy-run pace" && title !== "Benchmark history";
  return <div className="point-chart" role="group" aria-label={`${title}. ${description}`}>
    <svg aria-hidden="true" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M5 12H95 M5 50H95 M5 88H95" className="point-chart__grid" />{connect && coords.length > 1 && <polyline points={coords.map((point) => `${point.x},${point.y}`).join(" ")} className="point-chart__line" />}{lineValues?.map((value, index) => { if (index === 0 || value === null || lineValues[index - 1] === null) return null; const gap = (Date.parse(points[index].date) - Date.parse(points[index - 1].date)) / 86_400_000; return gap <= 42 ? <line key={points[index].id} x1={coords[index - 1].x} y1={pointPosition(lineValues[index - 1]!, min, max)} x2={coords[index].x} y2={pointPosition(value, min, max)} className="point-chart__trend" /> : null; })}</svg>
    {points.map((point, index) => <button key={point.id} type="button" className={`point-chart__point ${point.tone ? `is-${point.tone}` : ""} ${point.marker ? `has-${point.marker}` : ""}`} style={{ left: `${coords[index].x}%`, top: `${coords[index].y}%` }} aria-label={point.label}><span>{point.label}</span></button>)}
    <div className="point-chart__dates" aria-hidden="true"><span>{points[0].date}</span><span>{points.at(-1)!.date}</span></div>
  </div>;
}

function DataTable({ caption, headers, rows }: { caption: string; headers: string[]; rows: string[][] }) {
  return <details className="chart-data"><summary>View accessible data table</summary><div><table><caption className="sr-only">{caption}</caption><thead><tr>{headers.map((header) => <th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((cell, cellIndex) => cellIndex === 0 ? <th key={cellIndex} scope="row">{cell}</th> : <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></details>;
}

export default function ProgressGraphs({ store }: { store: TrainingStore }) {
  const today = trainingDateIso();
  const [range, setRange] = useState<ProgressRange>("8w");
  const [consistencyMode, setConsistencyMode] = useState<"distance" | "duration">("distance");
  const [benchmarkType, setBenchmarkType] = useState<BenchmarkEntry["type"] | "all">("all");
  const weeklyAll = useMemo(() => aggregateWeeklyGraph(activePlan, store.entries, store.checkIns, today), [store.entries, store.checkIns, today]);
  const weekly = weeklyAll.filter((week) => week.end >= rangeStart(range, today) && week.start <= today);
  const longRuns = filterByRange(selectLongRuns(store.entries, activePlan, store.checkIns), range, today);
  const easyRuns = filterByRange(selectComparableEasyRuns(store.entries), range, today);
  const benchmarksInRange = filterByRange(store.benchmarks, range, today);
  const benchmarks = filterBenchmarks(benchmarksInRange, benchmarkType);
  const maxConsistency = Math.max(1, ...weekly.flatMap((week) => consistencyMode === "distance" ? [week.plannedDistance, week.completedDistance] : [week.plannedDuration ?? 0, week.completedDuration]));
  const loadWeeks = weekly.filter((week) => week.load > 0 && week.sessions > 0);

  return <section className="progress-graphs" aria-label="Progress graphs">
    <header className="progress-graphs__controls"><div><p className="goal-page__eyebrow">Shared date range</p><h2>Training trends</h2></div><div role="group" aria-label="Graph date range">{(Object.keys(rangeLabels) as ProgressRange[]).map((item) => <button type="button" className={range === item ? "is-active" : ""} aria-pressed={range === item} key={item} onClick={() => setRange(item)}>{rangeLabels[item]}</button>)}</div></header>

    <article className="chart-card chart-card--wide" aria-labelledby="consistency-title" aria-describedby="consistency-description">
      <header><div><p className="chart-card__question">Is training volume building consistently while respecting recovery?</p><h3 id="consistency-title">Weekly training consistency</h3></div><div className="chart-toggle" role="group" aria-label="Consistency measurement"><button type="button" className={consistencyMode === "distance" ? "is-active" : ""} onClick={() => setConsistencyMode("distance")}>Distance</button><button type="button" className={consistencyMode === "duration" ? "is-active" : ""} onClick={() => setConsistencyMode("duration")}>Duration</button></div></header>
      <p className="chart-card__interpretation" id="consistency-description">{interpretConsistency(weekly)}</p>
      <div className="weekly-chart" role="img" aria-label={`Planned and completed weekly ${consistencyMode}. ${interpretConsistency(weekly)}`}>{weekly.map((week) => { const planned = consistencyMode === "distance" ? week.plannedDistance : week.plannedDuration ?? 0; const actual = consistencyMode === "distance" ? week.completedDistance : week.completedDuration; return <div className="weekly-chart__week" key={week.id}><div className="weekly-chart__bars"><i className="is-planned" style={{ height: `${planned / maxConsistency * 100}%` }} /><i className="is-completed" style={{ height: `${actual / maxConsistency * 100}%` }} /></div><strong>{week.start.slice(5)}</strong><small>{week.partial ? "Week in progress" : week.postRace ? "Post-race" : week.race ? "Race week" : week.recovery ? "Recovery" : "Completed week"}</small><span>{consistencyMode === "distance" ? `${actual.toFixed(1)}/${planned.toFixed(1)} mi` : `${Math.round(actual)}/${planned ? Math.round(planned) : "—"} min`}</span></div>; })}</div>
      <div className="chart-legend"><span><i className="is-planned" />Planned</span><span><i className="is-completed" />Completed</span></div>
      <DataTable caption="Weekly training consistency" headers={["Week", "Status", "Planned distance", "Completed distance", "Planned duration", "Completed duration", "4-week average"]} rows={weekly.map((week) => [week.label, week.partial ? "Week in progress" : week.recovery ? "Recovery" : week.race ? "Race" : "Complete", `${week.plannedDistance.toFixed(1)} mi`, `${week.completedDistance.toFixed(1)} mi`, formatMinutes(week.plannedDuration), formatMinutes(week.completedDuration), week.rollingDistance === null ? "Insufficient data" : `${week.rollingDistance.toFixed(1)} mi`])} />
    </article>

    <article className="chart-card" aria-labelledby="long-title" aria-describedby="long-description"><header><div><p className="chart-card__question">Are longer runs becoming more manageable?</p><h3 id="long-title">Long-run durability</h3></div></header><p className="chart-card__interpretation" id="long-description">{interpretLongRuns(longRuns)}</p><PointPlot title="Long-run durability" description={interpretLongRuns(longRuns)} points={longRuns.map((run) => ({ id: run.id, date: run.date, value: run.distance, tone: run.rpeBand, marker: run.pain !== "none" ? "pain" : run.recovery.startsWith("Delayed") ? "recovery" : undefined, label: `${run.date}: ${run.distance} miles, ${run.duration}, ${run.pace ?? "pace unavailable"}, average RPE ${run.averageRpe ?? "missing"}, ${run.rpeLabel}, ${run.elevation ?? "no"} feet elevation, ${run.terrain || "terrain unspecified"}, ${run.pain} pain, ${run.recovery}${run.cadence ? `, cadence ${run.cadence} spm` : ""}` }))} /><div className="chart-legend"><span><i className="dot is-easy" />RPE 3–4</span><span><i className="dot is-moderate" />RPE 5–6</span><span><i className="dot is-hard" />RPE 7–10</span><span>◇ Pain/recovery marker</span></div><DataTable caption="Long-run durability" headers={["Date", "Distance", "Duration", "Pace", "Average RPE", "Final RPE", "Terrain", "Elevation", "Pain", "Recovery"]} rows={longRuns.map((run) => [run.date, `${run.distance} mi`, run.duration, run.pace ?? "—", String(run.averageRpe ?? "—"), String(run.finalRpe ?? "—"), run.terrain || "—", run.elevation === null ? "—" : `${run.elevation} ft`, run.pain, run.recovery])} /></article>

    <article className="chart-card" aria-labelledby="easy-title" aria-describedby="easy-description"><header><div><p className="chart-card__question">Is easy running becoming faster at comparable effort?</p><h3 id="easy-title">Easy-run efficiency</h3></div></header><p className="chart-card__interpretation" id="easy-description">{interpretEasyRuns(easyRuns)}</p><PointPlot title="Easy-run pace" description={interpretEasyRuns(easyRuns)} points={easyRuns.map((run) => ({ id: run.id, date: run.date, value: -run.paceSeconds, marker: run.context || (run.elevation ?? 0) > 200 ? "context" : undefined, label: `${run.date}: ${run.pace}, RPE ${run.rpe}, ${run.terrain || "terrain unspecified"}, ${run.elevation ?? "no"} feet elevation${run.context ? `, ${run.context}` : ""}${run.heartRate ? `, average heart rate ${run.heartRate}` : ""}` }))} lineValues={easyRuns.map((run) => run.trend === null ? null : -run.trend)} /><div className="chart-legend"><span><i className="dot is-primary" />Raw pace</span><span><i className="line" />3-run rolling median</span><span>◇ Conditions marker</span></div><DataTable caption="Comparable easy runs" headers={["Date", "Pace", "RPE", "Terrain", "Elevation", "Heart rate", "Conditions"]} rows={easyRuns.map((run) => [run.date, run.pace, String(run.rpe), run.terrain || "—", run.elevation === null ? "—" : `${run.elevation} ft`, run.heartRate === null ? "—" : `${run.heartRate} bpm`, run.context || "—"])} /></article>

    <article className="chart-card chart-card--wide" aria-labelledby="benchmark-title" aria-describedby="benchmark-description"><header><div><p className="chart-card__question">Do controlled benchmarks support reviewing pace guidance?</p><h3 id="benchmark-title">Benchmark history</h3></div><label>Benchmark type<select value={benchmarkType} onChange={(event) => setBenchmarkType(event.target.value as BenchmarkEntry["type"] | "all")}><option value="all">All types</option><option>Controlled 5K</option><option>Controlled 10K</option><option>Repeatable tempo</option><option>Same easy route</option></select></label></header><p className="chart-card__interpretation" id="benchmark-description">{interpretBenchmarks(benchmarksInRange, benchmarkType)}</p><PointPlot title="Benchmark history" description={interpretBenchmarks(benchmarksInRange, benchmarkType)} points={benchmarks.map((entry) => ({ id: entry.id, date: entry.date, value: -(parseDurationMinutes(entry.duration) ?? 0), label: `${entry.date}: ${entry.type}, ${entry.duration}, ${benchmarkPace(entry) ?? "pace unavailable"}, RPE ${entry.averageRpe}, ${entry.terrain || "terrain unspecified"}, ${entry.elevationGain || "no"} feet elevation, ${entry.conditions || "conditions not recorded"}` }))} /><DataTable caption="Benchmark history" headers={["Date", "Type", "Time", "Pace", "RPE", "Terrain", "Elevation", "Conditions"]} rows={benchmarks.map((entry) => [entry.date, entry.type, entry.duration, benchmarkPace(entry) ?? "—", entry.averageRpe, entry.terrain || "—", entry.elevationGain ? `${entry.elevationGain} ft` : "—", entry.conditions || "—"])} /></article>

    <article className="chart-card chart-card--wide" aria-labelledby="load-title" aria-describedby="load-description"><header><div><p className="chart-card__question">How is estimated training load changing alongside recovery?</p><h3 id="load-title">Weekly session load and recovery</h3></div></header><p className="chart-card__interpretation" id="load-description">{interpretLoad(weekly)}</p>{loadWeeks.length >= GRAPH_THRESHOLDS.loadMinimumWeeks ? <><div className="load-chart" role="img" aria-label={interpretLoad(weekly)}>{loadWeeks.map((week) => <div key={week.id}><i style={{ height: `${week.load / Math.max(...loadWeeks.map((item) => item.load)) * 100}%` }} className={week.recoveryFlag || week.painFlag || week.hardSessions >= 2 ? "has-flag" : ""} /><span>{week.start.slice(5)}</span><small>{Math.round(week.load)}{week.recoveryFlag ? " · recovery" : week.painFlag ? " · pain" : week.hardSessions >= 2 ? " · hard" : ""}</small></div>)}</div><DataTable caption="Weekly session-load estimates" headers={["Week", "Load", "4-week trend", "Recovery flag", "Pain flag", "Too-hard sessions"]} rows={loadWeeks.map((week) => [week.label, String(Math.round(week.load)), week.rollingLoad === null ? "Insufficient data" : String(Math.round(week.rollingLoad)), week.recoveryFlag ? "Yes" : "No", week.painFlag ? "Yes" : "No", String(week.hardSessions)])} /></> : <div className="chart-empty">Add valid duration and session RPE for runs in at least two weeks to display this descriptive estimate.</div>}<p className="chart-card__disclaimer">Session load is duration in minutes × session RPE. It is not a medical risk score and does not estimate injury probability.</p></article>
  </section>;
}
